name: Build Android

on:
  push:
    paths:
      - 'mobile/**'
      - '.github/workflows/build-android.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    
    steps:
    - name: 🏗 Checkout repository
      uses: actions/checkout@v4

    - name: 🏗 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 🏗 Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        run_install: false

    - name: 📦 Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: 📦 Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('mobile/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: 📦 Install dependencies
      run: pnpm install

    - name: 🏗 Setup Expo CLI
      run: npm install -g @expo/cli

    - name: ☕ Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 🤖 Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: 🔨 Build Android APK
      run: |
        echo "🔨 Starting local Android build..."
        
        # Install dependencies and prebuild
        npx expo install --fix
        npx expo prebuild --platform android
        
        # Make gradlew executable
        chmod +x android/gradlew
        
        # Build the APK
        cd android
        ./gradlew assembleRelease --no-daemon
        
        echo "✅ Local build completed"

    - name: 📱 Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-${{ github.sha }}
        path: mobile/android/app/build/outputs/apk/release/*.apk